import os 

os.system ("sudo apt-get update")
os.system ("sudo apt-get install python3-setuptools")
os.system ("sudo apt-get install python3.7")
os.system ("sudo apt install python3-pip")
os.system ("sudo apt install python-pip")
os.system ("pip install --upgrade setuptools")
os.system ("pip3 install --upgrade setuptools")
os.system ("pip3 install boto3")
os.system ("pip3 install tinys3")
os.system ("pip3 install pyunpack")
os.system ("sudo apt-get install -y patool")
os.system ("pip3 install patool")
os.system ("pip install patool")
os.system ("pip3 install progress")
os.system ("sudo apt install python3-opencv")
os.system ("pip3 install opencv-python")
os.system ("sudo apt-get install libpq-dev")
os.system ("pip install psycopg2-binary")
os.system ("pip3 install psycopg2")
os.system ("pip install psycopg2")
os.system ("sudo apt-get -y upgrade")
os.system ("pip3 install python-binance --no-binary :all:")
os.system ("sudo apt-get update")
os.system ("sudo apt-get install postgresql postgresql-contrib")
os.system ("sudo apt install unzip")
os.system ("sudo apt-get upgrade")
